import 'package:vp_flutter/pages/eachView.dart';

const widgetNameList = [
  "AnimatedBuilder",
  "AnimatedContainer",
  "AnimatedCrossFade",
  "AnimatedDefaultTextStyle",
  "AnimatedSize",
  "AnimatedWidget",
  "AnimatedWidgetBaseState",
  "AnimatedListState",
  "AnimatedModalBarrier",
  "AnimatedOpacity",
  "AnimatedPhysicalModel",
  "AnimatedPositioned",
  "DecoratedBoxTransition",
  "FadeTransition",
  "FractionalTranslation",
  "Hero",
  "PositionedTransition",
  "RotationTransition",
  "ScaleTransition",
  "SlideTransition",
];

var widgetList = [
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
  EachView("Empty Demo", true),
];
